I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script call
    call defeat_mid_interogation
  File "game/script.rpy", line 112, in script
    with dissolve(3.0) #TODO for some reasion this here is not callable
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script call
    call defeat_mid_interogation
  File "game/script.rpy", line 112, in script
    with dissolve(3.0) #TODO for some reasion this here is not callable
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2752, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3674, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
eastern_medicine_project 1.0
Wed Nov 17 11:15:53 2021
